version: "3"

services:
  centos7:
    image: rpmbuild/centos7
    environment:
      DISTDIR: /home/builder/src
    volumes:
    - .:/srv
    entrypoint: /srv/pkg
    command: []
  centos8:
    image: dalibo/labs-sdk:centos8
    environment:
      DISTDIR: /home/builder/src
    volumes:
    - .:/srv
    entrypoint: /srv/pkg
    command: []
